# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../wazuh
patches:
- path: storage-class.yaml
- path: indexer/svc-resources.yaml
- path: indexer/sts-resources.yaml
- path: dashboard/svc-resources.yaml
- path: dashboard/sts-resources.yaml
- path: master/sts-resources.yaml
- path: master/svc-resources.yaml
- path: worker/sts-resources.yaml
- path: worker/svc-resources.yaml