apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-api-ingress
  namespace: wazuh
spec:
  rules:
    - host: "wazuh-api.local"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: wazuh
                port:
                  number: 55000